[book]
authors = ["Salsa Contributors"]
multilingual = false
src = "src"
title = "Salsa"

[build]
create-missing = false

[preprocess.links]

[output.html]
additional-css =["mermaid.css"]
additional-js =["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

